"""
Execution Domain Models

Immutable dataclasses representing execution requests, orders, fills, and reports.
All models are frozen to ensure deterministic, pure functional execution.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import List, Optional


class OrderType(Enum):
    """Order execution type"""
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"
    STOP_LIMIT = "STOP_LIMIT"
    TRAILING_STOP = "TRAILING_STOP"


class ExecutionPolicy(Enum):
    """Order time-in-force policy"""
    FOK = "FOK"
    IOC = "IOC"
    GTC = "GTC"
    DAY = "DAY"


class FillPolicy(Enum):
    """Order fill handling policy"""
    FULL_FILL = "FULL_FILL"
    PARTIAL_FILL = "PARTIAL_FILL"
    REJECT = "REJECT"


class ExecutionLifecycle(Enum):
    """Order lifecycle status"""
    REQUESTED = "REQUESTED"
    VALIDATED = "VALIDATED"
    QUEUED = "QUEUED"
    MATCHING = "MATCHING"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    SETTLED = "SETTLED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


@dataclass(frozen=True)
class ExecutionRequest:
    """Incoming request generated by the ML signal layer"""
    symbol: str
    side: str
    order_type: OrderType
    quantity: float
    price: Optional[float]
    execution_policy: ExecutionPolicy
    fill_policy: FillPolicy
    requested_at: datetime
    stop_price: Optional[float] = None
    trailing_delta: Optional[float] = None


@dataclass(frozen=True)
class ExecutionOrder:
    """Aggregated state tracking order execution parameters"""
    order_id: str
    request: ExecutionRequest
    status: ExecutionLifecycle
    cumulative_filled_qty: float
    average_filled_price: float
    active_price: Optional[float]
    created_at: datetime
    updated_at: datetime


@dataclass(frozen=True)
class ExecutionFill:
    """Immutable transaction record representing a filled order segment"""
    fill_id: str
    order_id: str
    symbol: str
    side: str
    quantity: float
    price: float
    commission: float
    slippage: float
    executed_at: datetime


@dataclass(frozen=True)
class ExecutionReport:
    """Update report returned to the orchestrator after a matching cycle"""
    order_id: str
    status: ExecutionLifecycle
    emitted_fills: List[ExecutionFill]
    remaining_quantity: float
    timestamp: datetime
    rejection_reason: Optional[str] = None
