"""Data contracts for Research Dashboard."""

from dataclasses import dataclass
from typing import Dict, Any, List, Optional


@dataclass(frozen=True)
class ResearchExperimentSummary:
    """Summary record of an experiment for listing views."""
    experiment_id: str
    name: str
    strategy_name: str
    created_at: str
    status: str
    metrics: Dict[str, float]


@dataclass(frozen=True)
class ExperimentDetail:
    """Full parameter configuration of an experiment."""
    experiment_id: str
    name: str
    description: str
    strategy_name: str
    parameters: Dict[str, Any]
    created_at: str
    status: str
    duration_seconds: float
    git_commit: str


@dataclass(frozen=True)
class FeatureLineageEntry:
    """Lineage entry for an associated feature dataset."""
    feature_dataset_id: str
    feature_version_id: str
    fingerprint: str


@dataclass(frozen=True)
class ExperimentLineage:
    """Lineage trace mapping an experiment to its source data roots."""
    experiment_id: str
    source_dataset_id: str
    source_dataset_fingerprint: str
    feature_datasets: List[FeatureLineageEntry]


@dataclass(frozen=True)
class ComparisonResult:
    """Comparison matrix across multiple experiments."""
    compared_ids: List[str]
    metrics_comparison: Dict[str, Dict[str, float]]
    parameter_differentials: Dict[str, Dict[str, Any]]


@dataclass(frozen=True)
class EvaluationSummary:
    """Evaluation summary metrics generated by backtest evaluation run."""
    experiment_id: str
    total_trades: int
    win_rate: float
    profit_factor: float
    average_trade_return: float
    daily_return_volatility: Optional[float]
    information_coefficient: Optional[float]
